const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //Admin
    //GENDER
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',
    //POSITION
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',
    //ROLE
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    //CREATE USER BUTTON
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
   //GET ALL USER
   FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
   FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
   //DELETE USER
   DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
   DELETE_USER_FAILED: 'DELETE_USER_FAILED',
   //EDIT USER
   EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
   EDIT_USER_FAILED: 'EDIT_USER_FAILED',
   //FETCH TOP DOCTOR
   FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
   FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',
   //FETCH_ALL_DOCTORS
   FETCH_All_DOCTORS_SUCCESS: 'FETCH_All_DOCTORS_SUCCESS',
   FETCH_All_DOCTORS_FAILED: 'FETCH_All_DOCTORS_FAILED',
   //SAVE DETAIL DOCTOR
   SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
   SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

})

export default actionTypes;